### ISSUE TITLE
Allow a non-contract address in _setLiquidityProvidersRewardContract 

### ISSUE THREAD

**Issue by varasev** [xdaichain/easy-staking-contracts#13]
Currently, `_setLiquidityProvidersRewardContract` requires the input address to be a contract. Let's change the requirement from `require(_contractAddress.isContract())` to `require(_contractAddress != address(0))` as we are not sure we will use a contract initially.

**Comment by maxaleks** [comment]
Done in https://github.com/xdaichain/easy-staking-contracts/commit/7857319ffaaf9bf38be0c715e050e722989fbbc1
