### ISSUE TITLE
Lock versions of all packages in `package.json`

### ISSUE THREAD

**Issue by varasev** [xdaichain/easy-staking-contracts#15]
Let's set explicit versions in `package.json`, e.g.

```
"@openzeppelin/contracts-ethereum-package": "2.5.0"
```

instead of

```
"@openzeppelin/contracts-ethereum-package": "^2.5.0"
```

This will help to prevent something in the code used from changing in the future.

**Comment by maxaleks** [comment]
Done in https://github.com/xdaichain/easy-staking-contracts/commit/a590ba39f455476bb75128c39dce48d283b5baf3
