### ISSUE TITLE
_setSigmoidParameters has incorrect message in `require`

### ISSUE THREAD

**Issue by varasev** [xdaichain/easy-staking-contracts#17]
Let's change the message inside `require` in [this line](https://github.com/xdaichain/easy-staking-contracts/blob/c3d37df16325242d001edc4b7e8bb9e1189d640c/contracts/EasyStaking.sol#L418) to `_a should be <= MAX_EMISSION_RATE/2`.

**Comment by maxaleks** [comment]
Done in https://github.com/xdaichain/easy-staking-contracts/commit/7d24799e62ec79aec93656078859995909bd5507
