### ISSUE TITLE
Consider enabling Solidity optimizer

### ISSUE THREAD

**Issue by varasev** [xdaichain/easy-staking-contracts#19]
I noticed that the Solidity optimizer is turned off in [truffle config](https://github.com/xdaichain/easy-staking-contracts/blob/c3d37df16325242d001edc4b7e8bb9e1189d640c/truffle.js#L26). Is any reason for keeping it disabled?

**Comment by maxaleks** [comment]
Done in https://github.com/xdaichain/easy-staking-contracts/commit/21cf8d3d065439cb92ccd9bff35d727df2696138
