### ISSUE TITLE
Unit test for the same id deposit reopening

### ISSUE THREAD

**Issue by varasev** [xdaichain/easy-staking-contracts#20]
Please, make sure we have a unit test for the case described in https://github.com/xdaichain/easy-staking-contracts/issues/6 - i.e. making a new deposit from scratch with the previously used `id` should work fine.

**Comment by maxaleks** [comment]
Done in https://github.com/xdaichain/easy-staking-contracts/commit/e94ee973b0e23888b280f33148c96444d5bc48a3
