### ISSUE TITLE
Extending claimTokens

### ISSUE THREAD

**Issue by varasev** [xdaichain/easy-staking-contracts#21]
Currently, `claimTokens` [doesn't allow](https://github.com/xdaichain/easy-staking-contracts/blob/c3d37df16325242d001edc4b7e8bb9e1189d640c/contracts/EasyStaking.sol#L222) claiming STAKE tokens from the balance of EasyStaking contract.

Consider changing [that requirement](https://github.com/xdaichain/easy-staking-contracts/blob/c3d37df16325242d001edc4b7e8bb9e1189d640c/contracts/EasyStaking.sol#L222) from `require(_token != address(token)` to `_token != address(token) || token.balanceOf(address(this)) > totalStaked` and add the corresponding description for `claimTokens` outlining when such a case can occur (after the owner of STAKE token contract [removes](https://github.com/xdaichain/stake-token/blob/v1.0.5/contracts/Token/ERC677MultiBridgeToken.sol#L54) the address of EasyStaking contract from the list of minters).

**Comment by maxaleks** [comment]
Done in https://github.com/xdaichain/easy-staking-contracts/commit/032658ef78662f9ddb522e891432929dcdeb94c9
