### ISSUE TITLE
Cover `sqrt` function by unit tests

### ISSUE THREAD

**Issue by varasev** [xdaichain/easy-staking-contracts#31]
to ensure it consumes an acceptable amount of gas for very big `x` and `c` parameters in the sigmoid function.

**Comment by maxaleks** [comment]
Done in https://github.com/xdaichain/easy-staking-contracts/commit/2364267999bd4fc76436db71b2b2fe0726b517c7

**Comment by varasev** [comment]
The test was improved a bit in https://github.com/xdaichain/easy-staking-contracts/commit/d35f704d58793c711fe458a1e85e0fdb0e1c5000
