### ISSUE TITLE
Add `userShare` to `Deposited` and `Withdrawn` events

### ISSUE THREAD

**Issue by varasev** [xdaichain/easy-staking-contracts#34]
I propose to add that field returned by the `_mint` function to those events (after `balance` field of the event).

**Comment by maxaleks** [comment]
Done in https://github.com/xdaichain/easy-staking-contracts/commit/6d460e02405bc9cc6f904754a9fe291278c8f936

**Comment by varasev** [comment]
Please, add a description for each `uint256 accruedEmission` parameter in those events.

**Comment by maxaleks** [comment]
Sorry, forgot about this. Added in https://github.com/xdaichain/easy-staking-contracts/commit/cb60511a343d9f3032e83663c4b350f5ee124395
