### ISSUE TITLE
Make denominator in `_getEmissionRateBasedOnTotalStakedAmount` function configurable by owner

### ISSUE THREAD

**Issue by varasev** [xdaichain/easy-staking-contracts#35]
Currently, `_getEmissionRateBasedOnTotalStakedAmount` calculates emission rate based on the `totalSupply`. The proposal is to make the supply in denominator configurable by the owner to be able to increase an emission APR making it closer to the upper bound of 7.5% if `totalStaked` is too small.

Such a denominator shouldn't exceed `totalSupply`.

**Comment by maxaleks** [comment]
Done in https://github.com/xdaichain/easy-staking-contracts/commit/c626db9e2352faede3d50ffac40ac3be129523f2
