### ISSUE TITLE
Unit tests for `getSupplyBasedEmissionRate`

### ISSUE THREAD

**Issue by varasev** [xdaichain/easy-staking-contracts#40]
Please ensure unit tests cover this condition: https://github.com/xdaichain/easy-staking-contracts/blob/2d6be8e43a7fb82e5875eeda8e1e7cb692ce46d9/contracts/EasyStaking.sol#L316-L318

**Comment by maxaleks** [comment]
Done in https://github.com/xdaichain/easy-staking-contracts/commit/268ef3eb2fcf0b5aef30c1a511fa194ccdce723e
