### ISSUE TITLE
Add events for the rest functions

### ISSUE THREAD

**Issue by varasev** [xdaichain/easy-staking-contracts#42]
We forgot to add events for the following functions:

setFee
setWithdrawalLockDuration
setWithdrawalUnlockDuration
setTotalSupplyFactor
setSigmoidParameters
setLiquidityProvidersRewardAddress

**Comment by maxaleks** [comment]
Added in https://github.com/xdaichain/easy-staking-contracts/commit/2dd09318459de7419ca0478a70419c01bfa0eec3

**Comment by varasev** [comment]
Please, add a non-indexed `address sender` parameter to each of the new events.

**Comment by varasev** [comment]
Done in https://github.com/xdaichain/easy-staking-contracts/commit/d1f41c8f2f36bcfbb36cf9410090691367ac4aeb
