### ISSUE TITLE
Improve deposit/withdraw unit tests

### ISSUE THREAD

**Issue by varasev** [xdaichain/easy-staking-contracts#43]
Let's add the following scenarios to the tests:

1. A user withdraws their entire deposit by several parts (more than two parts, different amounts for each part).

2. A user withdraws their balance (and emission) with the `amount` parameter set to zero and with `amount` set to the total deposit amount. The result in both cases should match (entire deposit withdrawal).

3. Different users make deposits and withdrawals and the `totalStaked` is changed correctly.

4. ~Ensure that date is reset to the current when replenishing the existing deposit.~

**Comment by maxaleks** [comment]
1-3 are added in https://github.com/xdaichain/easy-staking-contracts/commit/e2a5fcae30e10d236cd0f34f860854cebcba4474

**Comment by varasev** [comment]
The `totalStaked` test fails for me:

![image](https://user-images.githubusercontent.com/33550681/87002786-067f2200-c1c3-11ea-9403-cd19f5ee84cc.png)

**Comment by varasev** [comment]
I think the reason is that block timestamp fluctuates

**Comment by varasev** [comment]
Seems the same reason is in another test (in [this line](https://github.com/xdaichain/easy-staking-contracts/blob/e2a5fcae30e10d236cd0f34f860854cebcba4474/test/EasyStaking.test.js#L557)):

![image](https://user-images.githubusercontent.com/33550681/87003632-ac7f5c00-c1c4-11ea-82c6-759f85503643.png)

**Comment by varasev** [comment]
Rewrote the second test (`should withdraw the same amount`): https://github.com/xdaichain/easy-staking-contracts/commit/ff7b1d3bb41efeee1b5581930147c96b6ceca65d

**Comment by varasev** [comment]
The 3rd one is fixed in https://github.com/xdaichain/easy-staking-contracts/commit/544adc7cc66029880a089f641bd870181a37b041

**Comment by varasev** [comment]
> Ensure that date is not zeroed when replenishing the existing deposit.

Sorry, misprinted. I meant `Ensure that date is reset to the current when replenishing the existing deposit`. Such a test is already exists, so that's ok.
