### ISSUE TITLE
Options for staking multiple times

### ISSUE THREAD

**Issue by Jzjallday** [xdaichain/easy-staking-contracts#48]
Is it possible to combine staking into one grouping rather than separate groups each time you buy STAKE. For example, I bought STAKE deposited it in easy stake and the next day bought some more. When I went to deposit it, it automatically placed it in a new stake of its own. It would be beneficial if you could add them into 1, even if that meant forfeiting some of the time you initially staked on.

**Comment by varasev** [comment]
@Jzjallday it is supported by the EasyStaking contract (but not implemented in the [UI](https://easy-staking.xdaichain.com/) for simplicity): you can use the [`deposit(uint256 _depositId, uint256 _amount)`](https://github.com/xdaichain/easy-staking-contracts/blob/d5a477e4faf83d33901737cb461e97954ac4c1ec/contracts/EasyStaking.sol#L210-L229) function to add your STAKEs to an existing deposit. The `_depositId` is your existing deposit ID you wish to add a new amount to. You can invoke such a transaction on this page: https://etherscan.io/address/0xecbCd6D7264e3c9eAc24C7130Ed3cd2B38F5A7AD#writeProxyContract 

Before calling it, you first need to [approve](https://github.com/xdaichain/stake-token/blob/433c70d596e9c91632fe7d1a8da0464012dc15d8/contracts/Token/ERC20.sol#L80-L90) your amount (to let the EasyStaking contract take your tokens).

Please note that the function updates the deposit date to the current one.

**Comment by Jzjallday** [comment]
Thank you for the reply. To clarify, I am talking about moving a total amount plus the emissions from one account into another account on easystaking.

Right now I have 2 IDs both accruing emmissions on easy-staking. Take the following example for instance

ID 1 (10 stake + emissions)
ID 2 (20 stake plus emissions)

I'd like to move ID 1 with its emissions into ID 2

I think I understand initially but am confused how it will know what ID to pull it from. Do you have to initiate the scheduled withdraw on Easystaking for one of the accounts to have them approve the funds to be moved (in order to sign the contract)? Then once the 12 hour schedule has been competed I can interact with the etherscan contract (Adding the ID  I want to add funds to and the amount)

So between the 2 IDs it would look like this:

-ID # 1 Initiate Schedule withdraw on Easy stake for this account
-Wait 12 hours until withdraw is scheduled
-Enter [https://etherscan.io/address/0xecbCd6D7264e3c9eAc24C7130Ed3cd2B38F5A7AD#writeProxyContract](url)
-Add The transaction ID of the account that has not been approved on and the amount in the appropriate fields[deposit(uint256 _depositId, uint256 _amount)](url)
-press Write

What I'm confused on is how does it know which account to take it from? Seems more like this would be a transfer
Also, how does the transaction account for the emmissions that have accrued?

Your time and feedback is greatly appreciated.

**Comment by varasev** [comment]
After you call the `requestWithdrawal(uint256 _depositId)` with `_depositId = 1`, wait for 12 hours and then you can withdraw your requested tokens from the first deposit using the `makeRequestedWithdrawal(uint256 _depositId, uint256 _amount)`: you should call this function from your address and point `1` as the `_depositId`. To withdraw the entire amount with the emission, set the `_amount` parameter as `0`.

The above steps you can do with EasyStaking UI.

After you have withdrawn your tokens (deposit + emission), call the [`approve`](https://github.com/xdaichain/stake-token/blob/433c70d596e9c91632fe7d1a8da0464012dc15d8/contracts/Token/ERC20.sol#L80-L90) function of the STAKE token contract (not EasyStaking contract) to approve the new amount you want to stake into the second deposit. After that, you need to call the `deposit(uint256 _depositId, uint256 _amount)` from the same address (you used initially to make both deposits) to add the amount to the second deposit (`_depositId = 2`). It will accrue emission to your second deposit (as if you would re-deposited it), reset the deposit's date, and add the new `_amount` to its balance.

> What I'm confused on is how does it know which account to take it from?

By account you mean your Ethereum address, right? When you call the smart contract's function, it takes the caller's address from the `from` field of the transaction (and uses `msg.sender` field in the contract).

**Comment by Jzjallday** [comment]
Thank you, I should be able to figure it out from here. I appreciate it!

**Comment by varasev** [comment]
Ok, I'm closing this issue.
