### ISSUE TITLE
Deposit ID checking

### ISSUE THREAD

**Issue by varasev** [xdaichain/easy-staking-contracts#6]
I have a little concern regarding [this line](https://github.com/xdaichain/easy-staking-contracts/blob/9cc01b76abf6321f8e260292155f9f1f45f09c15/contracts/EasyStaking.sol#L145) - AFAIU, it checks whether the deposit with the specified id exists, or not.

But what if some deposit was created and then fully closed? In this case, the specified id will be in the range `_depositId > 0 && _depositId <= lastDepositIds[msg.sender]`, but `balances[_sender][_id]` and `depositDates[_sender][_id]` will be zero, so the user will be able to create a deposit with the same ID again.

Maybe we should also check the balance for zero? To avoid an ability to create a new deposit having an old ID.

**Comment by maxaleks** [comment]
I don't think we should add this check because the current logic doesn't brake anything. It may also be more convenient for exchanges.

**Comment by varasev** [comment]
But it may be confusing to see the `Deposited` event for the same `sender+id` key twice for newly opened deposit. E.g., each bank account has its unique number: when we close the account, it will never be used again (and shouldn't in legal purposes). So I think if some `id` was used and then was closed, it shouldn't be reused again.

**Comment by maxaleks** [comment]
We decided to leave it as it is
