### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by varasev** [xdaichain/easy-staking-contracts#7]
Please fully review and update README according to the latest changes

**Comment by maxaleks** [comment]
Updated in https://github.com/xdaichain/easy-staking-contracts/commit/c7325ec83218bd012e8022139816658febe85899

**Comment by varasev** [comment]
README should be updated again after https://github.com/xdaichain/easy-staking-contracts/issues/35 is implemented

**Comment by maxaleks** [comment]
Updated in https://github.com/xdaichain/easy-staking-contracts/commit/4bb7e739568ba94bab41707ba87ecfe4edfd0044
