### ISSUE TITLE
Consider a negative `b` sigmoid param

### ISSUE THREAD

**Issue by varasev** [xdaichain/easy-staking-contracts#8]
The sigmoid function contains `x - b` expression which allows moving sigmoid to left and right (depending on the sign of `b`), but the current `b` in the contract is `uint256`, i.e. always positive. Consider making it `int256`.

**Comment by maxaleks** [comment]
Done in https://github.com/xdaichain/easy-staking-contracts/commit/6c7bcd2205f8caee53e24f53218829d43dd935ec
